src/Entity/Hours.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HoursRepository")
 */
class Hours
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Absence", mappedBy="hours")
     */
    private $absences;

    /**
     * @ORM\Column(type="time")
     */
    private $begin;

    /**
     * @ORM\Column(type="time")
     */
    private $end;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ord;

    public function __construct()
    {
        $this->absences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Absence[]
     */
    public function getAbsences(): Collection
    {
        return $this->absences;
    }


    /**
     * @return Collection|Absence[]
     */
    public function getTodayAbsences(): Collection
    {
        return $this->getAbsences()->filter(function (Absence $absenceList) {
            $today = new \DateTime();

            if ($absenceList->getFinalDay() == null) {
                return $absenceList->getDay()->format("Y-m-d") == $today->format("Y-m-d");
            } else {
                return $today->format("Y-m-d") >= $absenceList->getDay()->format("Y-m-d") and $today->format("Y-m-d") <= $absenceList->getFinalDay()->format("Y-m-d");
            }

        });
    }


    public function addFalta(Absence $absence): self
    {
        if (!$this->absences->contains($absence)) {
            $this->absences[] = $absence;
            $absence->addHour($this);
        }

        return $this;
    }

    public function removeFalta(Absence $absence): self
    {
        if ($this->absences->contains($absence)) {
            $this->absences->removeElement($absence);
            $absence->removeHour($this);
        }

        return $this;
    }

    public function getBegin(): ?\DateTimeInterface
    {
        return $this->begin;
    }

    public function setBegin(\DateTimeInterface $begin): self
    {
        $this->begin = $begin;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getOrd(): ?int
    {
        return $this->ord;
    }

    public function setOrd(?int $ord): self
    {
        $this->ord = $ord;

        return $this;
    }
}

src/Entity/Teacher.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass="App\Repository\TeacherRepository")
 * @UniqueEntity(fields={"dni"}, message="There is already an account with this dni")
 * @Vich\Uploadable
 */
class Teacher implements UserInterface
{

    public function __construct()
    {
        $this->absences = new ArrayCollection();
        $this->extraCurriculars = new ArrayCollection();
        $this->meetings = new ArrayCollection();
        $this->teacherActivityInscriptions = new ArrayCollection();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $dni;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Absence", mappedBy="teacher", orphanRemoval=true)
     */
    private $absences;


    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="teacher_image", fileNameProperty="pic")
     *
     * @var File
     */
    private $imageFile;



    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     *
     */
    private $pic;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\ExtraCurricular", mappedBy="teachers")
     */
    private $extraCurriculars;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Meetings", mappedBy="teachers")
     */
    private $meetings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TeacherActivityInscription", mappedBy="teacher")
     */
    private $teacherActivityInscriptions;

    /**
     *
     * @param File|UploadedFile $imageFile
     * @throws Exception
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDni(): ?string
    {
        return $this->dni;
    }

    public function setDni(string $dni): self
    {
        $this->dni = $dni;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->dni;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_PROFESOR';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getPic(): ?string
    {
        return $this->pic;
    }

    public function setPic(?string $pic): self
    {
        $this->pic = $pic;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCompleteUserName()
    {
        return $this->getUsername().' - '.$this->getFullName();
    }

    public function getFullName()
    {
        return $this->name.', '.$this->surname;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }


    /**
     * @return Collection|Absence[]
     */
    public function getAbsences(): Collection
    {
        return $this->absences;
    }

    public function addAbsence(Absence $absence): self
    {
        if (!$this->absences->contains($absence)) {
            $this->absences[] = $absence;
            $absence->setMotivation($this);
        }

        return $this;
    }

    public function removeAbsence(Absence $absence): self
    {
        if ($this->absences->contains($absence)) {
            $this->absences->removeElement($absence);
            // set the owning side to null (unless already changed)
            if ($absence->getMotivation() === $this) {
                $absence->setMotivation(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ExtraCurricular[]
     */
    public function getExtraCurriculars(): Collection
    {
        return $this->extraCurriculars;
    }

    public function addExtraCurricular(ExtraCurricular $extraCurricular): self
    {
        if (!$this->extraCurriculars->contains($extraCurricular)) {
            $this->extraCurriculars[] = $extraCurricular;
            $extraCurricular->addTeacher($this);
        }

        return $this;
    }

    public function removeExtraCurricular(ExtraCurricular $extraCurricular): self
    {
        if ($this->extraCurriculars->contains($extraCurricular)) {
            $this->extraCurriculars->removeElement($extraCurricular);
            $extraCurricular->removeTeacher($this);
        }

        return $this;
    }

    /**
     * @return Collection|Meetings[]
     */
    public function getMeetings(): Collection
    {
        return $this->meetings;
    }

    public function addMeeting(Meetings $meeting): self
    {
        if (!$this->meetings->contains($meeting)) {
            $this->meetings[] = $meeting;
            $meeting->addTeacher($this);
        }

        return $this;
    }

    public function removeMeeting(Meetings $meeting): self
    {
        if ($this->meetings->contains($meeting)) {
            $this->meetings->removeElement($meeting);
            $meeting->removeTeacher($this);
        }

        return $this;
    }

    /**
     * @return Collection|TeacherActivityInscription[]
     */
    public function getTeacherActivityInscriptions(): Collection
    {
        return $this->teacherActivityInscriptions;
    }

    public function addTeacherActivityInscription(TeacherActivityInscription $teacherActivityInscription): self
    {
        if (!$this->teacherActivityInscriptions->contains($teacherActivityInscription)) {
            $this->teacherActivityInscriptions[] = $teacherActivityInscription;
            $teacherActivityInscription->setTeacher($this);
        }

        return $this;
    }

    public function removeTeacherActivityInscription(TeacherActivityInscription $teacherActivityInscription): self
    {
        if ($this->teacherActivityInscriptions->contains($teacherActivityInscription)) {
            $this->teacherActivityInscriptions->removeElement($teacherActivityInscription);
            // set the owning side to null (unless already changed)
            if ($teacherActivityInscription->getTeacher() === $this) {
                $teacherActivityInscription->setTeacher(null);
            }
        }

        return $this;
    }
}

src/Form/AbsenceType.php
<?php

namespace App\Form;

use App\Entity\Absence;
use App\Entity\Hours;
use App\Entity\Permissions;
use App\Entity\Teacher;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\AbstractType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Contracts\Translation\TranslatorInterface;
use Doctrine\ORM\EntityRepository;


class AbsenceType extends AbstractType
{

    private $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $user = $options['user'];

        $builder->add('day', DateType::class, [

                'label_format' => 'nueva.ausencia.dia',
                'widget' => 'single_text',
            ]
        )
            ->add('work', CheckBoxType::class, [

                    'label_format' => 'nueva.ausencia.trabajo',
                    'required' => false,
                ]
            )
            ->add('commentAlu', TextareaType::class, ['required' => false, 'label_format' => 'nueva.ausencia.comentalu',])
            ->add('commentDir', TextareaType::class, ['required' => false, 'label_format' => 'nueva.ausencia.comentdir',])
            ->add('motivation', EntityType::class, [
                'class' => Permissions::class,
                'choice_label' => 'description',
                'placeholder' => $this->translator->trans('nueva.ausencia.motivo.ph'),

                'label_format' => 'nueva.ausencia.motivo',
            ])
            ->add('hours', EntityType::class, [
                'class' => Hours::class,
                'choice_label' => 'description',
                'multiple' => true,
                'expanded' => true,
                'label_format' => 'nueva.ausencia.horas',
                'attr' => ['class' => 'hours-check'],
            ]);

        if (in_array("ROLE_DIRECTIVA", $user->getRoles())) {

            $builder->add('teacher', EntityType::class, [
                'class' => Teacher::class,
                'choice_label' => 'completeusername',
                'preferred_choices' => array($user)

            ]);
        } else {

            $builder->add('teacher', EntityType::class, [
                'class' => Teacher::class,
                'query_builder' => function (EntityRepository $er) use (&$user) {

                    return $er->createQueryBuilder('tq')
                        ->select('t')
                        ->from('App\Entity\Teacher', 't')
                        ->where('t.id = ?1')
                        ->setParameter(1, $user->getId());
                },
                'choice_label' => 'completeusername',
                'disabled' => true,
            ]);
        }


        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $absence = $event->getData();
            $form = $event->getForm();
            if ((!$absence || null === $absence->getId()) || ($absence != null && $absence->getFinalDay() == null)) {
                $form->add('type', ChoiceType::class, [
                    'choices' => [$this->translator->trans('nueva.ausencia.dia') => "day", $this->translator->trans('nueva.ausencia.periodo') => "period"],

                    'label_format' => 'nueva.ausencia.tipo',
                    'expanded' => true,
                    'attr' => ['class' => 'form-check-inline'],
                    'data' => "day",
                ]);

                $form->add('finalDay', DateType::class, [

                        'label_format' => 'nueva.ausencia.hasta',
                        'label_attr' => ['hidden' => 'true'],
                        'widget' => 'single_text',
                        'required' => false,
                        'attr' => ['hidden' => 'true'],
                    ]
                );
            } elseif ($absence != null && $absence->getFinalDay() != null) {
                $form->add('type', ChoiceType::class, [
                    'choices' => [$this->translator->trans('nueva.ausencia.dia') => "day", $this->translator->trans('nueva.ausencia.periodo') => "period"],

                    'label_format' => 'nueva.ausencia.tipo',
                    'expanded' => true,
                    'attr' => ['class' => 'form-check-inline'],
                    'data' => "period",
                ]);

                $form->add('finalDay', DateType::class, [

                        'label_format' => 'nueva.ausencia.hasta',
                        'widget' => 'single_text',
                        'required' => true,
                    ]
                );
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Absence::class,
            'user' => null
        ]);
    }
}

templates/absence/_delete_form.html.twig
<form method="post" action="{{ path('absence_delete', {'id': absence.id}) }}" onsubmit="return confirm('¿Seguro que quieres eliminar el elemento?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ absence.id) }}">
    <button class="btn btn-outline-danger">ELIMINAR</button>
</form>

templates/absence/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{{ form_start(form) }}
    {{ form_row(form.teacher) }}
    {{ form_row(form.type) }}
    {{ form_row(form.day) }}
    {{ form_row(form.finalDay) }}
    {{ form_rest(form) }}
{#{ form_end(form) }#}

templates/absence/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edición Ausencia{% endblock %}

{% block body %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent">
            <li class="breadcrumb-item"><a href="{{ path('home') }}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{{ path('absence_index') }}">Ausencias</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edición</li>
        </ol>
    </nav>

    <h1>Edición Ausencia</h1>

    <div class="btn-toolbar toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group mr-2" role="group" aria-label="Second group">
            {{ include('absence/_delete_form.html.twig') }}
        </div>
        <div class="btn-group mr-2" role="group" aria-label="Thirth group">
            <a href="{{ path('absence_index') }}" class="btn btn-outline-danger">VOLVER</a>
        </div>
    </div>

    <div class="form">
        {{ include('absence/_form.html.twig', {'button_label': 'Update'}) }}
    </div>

    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group mr-2" role="group" aria-label="First group">
            <button class="btn btn-outline-danger" type="submit">{{ "form.enviar"|trans }}</button>
        </div>
        <div class="btn-group mr-2" role="group" aria-label="Thirth group">
            <a href="{{ path('absence_index') }}" class="btn btn-outline-danger">{{ "form.volver"|trans }}</a>
        </div>
    </div>

    <div class="form-check" id="all_day_div">
        <input type="checkbox" id="all_day_check"  class="form-check-input" name="all_day[]">
        <label class="form-check-label" for="all_day_check">{{ "form.todo.dia"|trans }}</label>
    </div>
    </form>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('absence') }}
{% endblock %}

templates/absence/proof.html.twig
{% extends 'proof-base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}


    <div class="proof-header" style="margin:0 auto;text-align: center;">
        <img src="{{ absolute_url(asset("img/proof-header.png")) }}" width="80%"/>
    </div>
    <div class="proof-body">

        <div style="width: 80%;margin:0 auto;margin-top: 35px;">
            El/La <span style="font-weight: bold">professor/a </span> {{ absence.teacher.fullName }}
        </div>
        <div style="width: 80%;margin:0 auto;margin-top: 15px;">
            Ha faltat a classe els dies i hores que al requadre s'indiquen, pels motius que s'epressen
        </div>

        <table style="width: 80%;margin:0 auto;margin-top:15px;text-align: center;" class="bordered">
            <thead>
            <th>MOTIU</th>
            <th>CODI</th>
            </thead>
            <tbody>
            <tr>
                <td style="font-weight: bold;"></td>
                <td>{{ absence.motivation.description }}</td>
            </tr>
            </tbody>
        </table>

        <table style="width: 80%;margin:0 auto;text-align: center;margin-top:15px;" class="bordered">
            <thead>
            <th>DÍA/PERIODE</th>
            <th>HORES</th>
            <th>ACTIVITAT</th>
            </thead>

            <tbody>

            <tr>
                {% if absence.finalDay %}
                    <td>{{ absence.day|date('d-m-Y') }} a {{ absence.finalDay|date('d-m-Y') }}</td>

                {% else %}
                    <td>{{ absence.day|date('d-m-Y') }}</td>
                {% endif %}
                <td>{% if absence.hours.count > 1 %}
                        {{ absence.hours|first.description }} a {{ absence.hours|last.description }}
                    {% else %}
                        {{ absence.hours|first.description }}
                    {% endif %}</td>
                <td>XXXX</td>
            </tr>
            </tbody>
        </table>
    </div>
    </div>

    <div class="proof-footer"
         style="width:80%;margin:0 auto;margin-top: 20px;border-style: solid;border-width:thin;border-color: #222222;padding: 15px;">
        <div>Adjunte justificant: <span>SÍ</span><span style="margin-left:15px;">NO</span></div>
        <div style="text-align:center;margin:0 auto;margin-top:5px;">Mutxamel, a {{ "now"|date("d") }} de
            {% set text = "" %}
            {% set month = "now"|date("m") %}
            {% if month == 2 %}
                Febrer
            {% endif %}
            de {{ "now"|date("Y") }}</div>
        <div style="text-align:center;margin:0 auto;margin-top:65px;">
            Signatura del/de la professor/a
        </div>
    </div>


    <div class="proof-footer"
         style="width:80%;margin:0 auto;margin-top: 20px;border-style: solid;border-width:thin;border-color: #222222;padding:15px;">
        <div style="text-align: center;">Vistes les raons al.legades i considerant motiu transitori i no previsible la sol.licitud de permís, LA DIRECCIÓ justifica l'absència a tots els efectes</div>
        <div style="text-align:center;margin:0 auto;margin-top:5px;">Mutxamel, a {{ "now"|date("d") }} de
            {% set text = "" %}
            {% set month = "now"|date("m") %}
            {% if month == 2 %}
                Febrer
            {% endif %}
            de {{ "now"|date("Y") }}</div>
        <div style="text-align:center;margin:0 auto;margin-top:65px;">
            La Directora
        </div>
    </div>
{% endblock %}

templates/absence/teachers.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div id="timetable_teachers" class="table-responsive">

        <div id="toggle_container">
            <button id="toggle_fullscreen" type="button" class="btn btn-danger btn-sm" style="margin-bottom: 10px;">Pantalla Completa</button>
        </div>
        <table class="table table-bordered text-center">
            <thead class="thead-dark">
            <tr class="">
                <th class="col-1 w-auto">HORA</th>
                <th class="col-3 w-auto ">PROFESORES/AS AUSENTES</th>
                <th class="col-1 w-auto ">DEJA TRABAJO</th>
                <th class="col-2 w-auto">CURSO</th>
                <th class="col-1 w-auto">AULA</th>
                <th class="col-3 w-auto">PROFESORES/AS GUARDIA</th>
            </tr>
            </thead>
            <tbody>

            {% for hour in hours %}

                {% if hour.todayAbsences.count > 0 %}

                    {% if "now"|date("H:i") >= hour.begin|date('H:i') and "now"|date("H:i") <= hour.end|date('H:i') %}
                        <tr class="bg-warning text-white">

                        <td rowspan="{{ hour.todayAbsences.count }}"
                            class="col-1 w-auto hour_desc font-weight-bold"
                            data="{{ hour.description }}"
                            original="{{ hour.begin|date('H:i') }} - {{ hour.end|date('H:i') }}">
                            {{ hour.begin|date('H:i') }}
                            - {{ hour.end|date('H:i') }}
                        </td>
                        <td class="col-3 w-auto"><a class="absenceTimeTableLinkWhite"
                                                    href="{{ path('absence_show',{id:hour.todayAbsences|first.id}) }}">{{ hour.todayAbsences|first.teacher.fullname }}</a>
                        </td>
                    {% else %}
                        <tr class="">

                        <td rowspan="{{ hour.todayAbsences.count }}" class="col-1 w-auto hour_desc font-weight-bold"
                            data="{{ hour.description }}"
                            original="{{ hour.begin|date('H:i') }} - {{ hour.end|date('H:i') }}">
                            {{ hour.begin|date('H:i') }}
                            - {{ hour.end|date('H:i') }}
                        </td>
                        <td class="col-3 w-auto"><a class="absenceTimeTableLinkBlack"
                                                    href="{{ path('absence_show',{id:hour.todayAbsences|first.id}) }}">{{ hour.todayAbsences|first.teacher.fullname }}</a>
                        </td>
                    {% endif %}


                    <td class="col-1 w-auto">{{ hour.todayAbsences|first.work ? 'SÍ' : 'NO' }}</td>
                    <td class="col-2 w-auto">1FBB ADM.</td>
                    <td class="col-1 w-auto">INFO1</td>

                    {% if "now"|date("H:i") >= hour.begin|date('H:i') and "now"|date("H:i") <= hour.end|date('H:i') %}
                        <td class="col- w-auto " rowspan="{{ hour.todayAbsences.count }}">Fulano y
                            mengano
                        </td>
                    {% else %}
                        <td class="col-3 w-auto" rowspan="{{ hour.todayAbsences.count }}">Fulano y mengano</td>
                    {% endif %}
                    </tr>
                    {% for absence in hour.todayAbsences|slice(1, hour.todayAbsences.count) %}

                        {% if "now"|date("H:i") >= hour.begin|date('H:i') and "now"|date("H:i") <= hour.end|date('H:i') %}
                            <tr class="bg-warning  text-white">
                            <td class="col-3 w-auto"><a class="absenceTimeTableLinkWhite"
                                                        href="{{ path('absence_show',{id:absence.id}) }}">{{ absence.teacher.fullname }}</a>
                            </td>
                        {% else %}
                            <tr class="">
                            <td class="col-3 w-auto"><a class="absenceTimeTableLinkBlack"
                                                        href="{{ path('absence_show',{id:absence.id}) }}">{{ absence.teacher.fullname }}</a>
                            </td>
                        {% endif %}


                        <td class="col-1 w-auto">{{ absence.work ? 'SÍ' : 'NO' }}</td>
                        <td class="col-2 w-auto">1FBB ADM.</td>
                        <td class="col-1 w-auto">INFO1</td>

                        </tr>

                    {% endfor %}
                {% else %}

                    {% if "now"|date("H:i") >= hour.begin|date('H:i') and "now"|date("H:i") <= hour.end|date('H:i') %}
                        <tr class="bg-success  text-white">
                        <td class="col-1 w-auto hour_desc  font-weight-bold" data="{{ hour.description }}"
                            original="{{ hour.begin|date('H:i') }} - {{ hour.end|date('H:i') }}">
                            {{ hour.begin|date('H:i') }}
                            - {{ hour.end|date('H:i') }}
                        </td>
                    {% else %}
                        <tr class="">
                        <td class="col-1 w-auto hour_desc font-weight-bold" data="{{ hour.description }}"
                            original="{{ hour.begin|date('H:i') }} - {{ hour.end|date('H:i') }}">
                            {{ hour.begin|date('H:i') }}
                            - {{ hour.end|date('H:i') }}
                        </td>
                    {% endif %}

                    <td class="col-3 w-auto">SIN AUSENCIAS</td>
                    <td class="col-1 w-auto">-</td>
                    <td class="col-2 w-auto">-</td>
                    <td class="col-1 w-auto">-</td>
                    <td class="col-4 w-auto">Fulano y mengano</td>
                    </tr>
                {% endif %}
            {% endfor %}

            </tbody>
        </table>

    </div>

{% endblock %}


{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('teachers') }}
{% endblock %}